version: '3.8'
services:
  cs_esp:
    container_name: cs_esp
    image: cs_esp:latest
    restart: always
    environment:
      - TZ=America/New_York
    volumes:
      - ./volumes/cs_esp/log:/cs_esp/log

networks:
  default:
    name: ${HOSTNAME}
