version: '3.8'
services:
  cs_esphome:
    container_name: cs_esphome
    image: cs_esphome:latest
    restart: always
    environment:
      - TZ=America/New_York
    volumes:
      - ./volumes/cs_esphome/log:/cs_esphome/log

networks:
  default:
    name: ${HOSTNAME}
