version: '3.8'
services:
  esphome:
    container_name: esphome
    image: esphome:latest
    restart: always
    environment:
      - TZ=America/New_York
    volumes:
      - ./volumes/esphome/log:/esphome/log

networks:
  default:
    name: ${HOSTNAME}
