{
 "title": "CircuitSetup",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   { "name": "period", "label": "Display Period", "query": "Today, Month, Year" }
  ]
 },
 "panels": [
  {
   "title": "Net Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "production = from(bucket: \"multisma2\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"power\" and r._inverter == \"site\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"production\")\n  \nconsumption = from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"line\")\n  |> map(fn: (r) => ({ r with _time: r._time, _value: r._value * -1.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"consumption\")\n\nunion(tables: [production, consumption])\n  |> drop(columns: [\"_inverter\", \"_measurement\", \"_start\", \"_stop\"])\n  |> truncateTimeColumn(unit: 10s)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with Delta: r.power + r.line }))\n  |> yield(name: \"union\")\n\n"
    }
   ]
  },
  { "title": "${period} (kWh)", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 14, "y": 0 } },
  {
   "title": "${period} Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "repeat": "Periods",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"_kitchen\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, Kitchen:\n      if not exists r._kitchen or r._kitchen == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r._kitchen / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"_basement\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, Basement:\n      if not exists r._basement or r._basement == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r._basement / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"_vehicles\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, Vehicles:\n      if not exists r._vehicles or r._vehicles == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r._vehicles / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"_bedroom\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, Bedrooms:\n      if not exists r._bedroom or r._bedroom == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r._bedroom / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"_laundry\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, Laundry:\n      if not exists r._laundry or r._laundry == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r._laundry / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"hot_water\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, HotWater:\n      if not exists r.hot_water or r.hot_water == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r.hot_water / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"heatpump\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, HeatPump:\n      if not exists r.heatpump or r.heatpump == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r.heatpump / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"_main_floor\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, MainFloor:\n      if not exists r._main_floor or r._main_floor == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else r._main_floor / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and (r._device == \"metered\" or r._device == \"line\"))\n  |> drop(columns: [\"_location\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, Unmetered:\n      if not exists r.metered or r.metered == 0.0 then 0.0\n      else if not exists r.line or r.line == 0.0 then 0.0\n      else if (r.line - r.metered) <= 0.0 then 0.0\n      else (r.line - r.metered) / r.line * 100.0 } ))\n  |> yield(name: \"device\")\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"consumption\")\n"
    }
   ]
  },
  {
   "title": "Kitchen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"_kitchen\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"consumption\")\n"
    }
   ]
  },
  {
   "title": "Heat pump",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"heatpump\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"consumption\")\n"
    }
   ]
  },
  {
   "title": "30 Day Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"multisma2\")\n  |> range(start: -31d)\n  |> filter(fn: (r) => r._measurement == \"production\" and r._inverter == \"site\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Production: r._value }))\n  |> yield(name: \"production\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -31d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Consumption: r._value * -0.001}))\n  |> yield(name: \"consumption\")\n"
    },
    {
     "query": "c1 = from(bucket: \"cs24\")\n  |> range(start: -60d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_device\"] == \"line\")\n  |> filter(fn: (r) => r[\"_field\"] == \"today\")\n  |> movingAverage(n: 30)\n  |> map(fn: (r) => ({ _time: r._time, _movavg: r._value * -0.001}))\n  |> yield(name: \"c1\")\n\nm1 = from(bucket: \"multisma2\")\n  |> range(start: -60d)\n  |> filter(fn: (r) => r._measurement == \"production\" and r._inverter == \"site\" and r._field == \"today\")\n  |> movingAverage(n: 30)\n  |> map(fn: (r) => ({ _time: r._time, _movavg: r._value }))\n  |> yield(name: \"m1\")\n\njoin(tables: {d1: c1, d2: m1}, on: [\"_time\"])\n  |> drop(columns: [\"_movavg\"])\n  |> map(fn: (r) => ({ _time: r._time, Trend: r._movavg_d1 + r._movavg_d2}))\n  |> yield(name: \"c1m1\")\n"
    }
   ]
  },
  {
   "title": "Line Characteristics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"line\" or r[\"_field\"] == \"l1\" or r[\"_field\"] == \"l2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "${period} Use (kWh) ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"_kitchen\")\n  |> map(fn: (r) => ({ _value: r._device, Kitchen: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"kitchen\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"_basement\")\n  |> map(fn: (r) => ({ _value: r._device, Basement: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"basement\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"_vehicles\")\n  |> map(fn: (r) => ({ _value: r._device, EVCharging: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"vehicles\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"_bedroom\")\n  |> map(fn: (r) => ({ _value: r._device, Bedrooms: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"bedroom\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"_laundry\")\n  |> map(fn: (r) => ({ _value: r._device, Laundry: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"laundry\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"hot_water\")\n  |> map(fn: (r) => ({ _value: r._device, HotWater: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"hotwater\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"heatpump\")\n  |> map(fn: (r) => ({ _value: r._device, Heatpump: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"heatpump\")\n"
    },
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"_main_floor\")\n  |> map(fn: (r) => ({ _value: r._device, MainFloor: r._value * 0.001 } ))\n  |> toString()\n  |> yield(name: \"mainfloor\")\n"
    }
   ]
  },
  {
   "title": "Hot water",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"hot_water\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"hot_water\")\n"
    }
   ]
  },
  {
   "title": "EV Charging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"_vehicles\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"_vehicles\")\n"
    }
   ]
  },
  {
   "title": "12 Month Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"cs24\")\n  |> range(start: -13mo, stop: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_device\"] == \"line\")\n  |> filter(fn: (r) => r[\"_field\"] == \"month\")\n  |> map(fn: (r) => ({ _time: r._time, Previous: r._value * 0.001}))\n  |> yield(name: \"past\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_device\"] == \"line\")\n  |> filter(fn: (r) => r[\"_field\"] == \"month\")\n  |> map(fn: (r) => ({ _time: r._time, Current: r._value * 0.001}))\n  |> yield(name: \"current\")\n"
    }
   ]
  },
  {
   "title": "Heatpump & Hot Water",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"hot_water\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"hot_water\")"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"heatpump\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"heatpump\")"
    }
   ]
  },
  {
   "title": "Bedrooms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"_bedroom\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"_bedroom\")\n"
    }
   ]
  },
  {
   "title": "${period} Use (kWh)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => r._device == \"heatpump\" or\n                       r._device == \"hot_water\" or\n                       r._device == \"_kitchen\" or\n                       r._device == \"_laundry\" or\n                       r._device == \"_bedroom\" or\n                       r._device == \"_basement\" or\n                       r._device == \"_main_floor\" or\n                       r._device == \"_vehicles\"\n                    )\n  |> map(fn: (r) => ({ _value: r._device, _kwh: r._value * 0.001 }))\n  |> toString()\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_field\"])\n  |> yield(name: \"results\")\n"
    }
   ]
  },
  {
   "title": "Basement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"_basement\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"_basement\")\n"
    }
   ]
  },
  {
   "title": "Laundry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"_laundry\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"laundry\")\n"
    }
   ]
  },
  {
   "title": "30 Day Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"cs24\")\n  |> range(start: -31d, stop: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_device\"] == \"line\")\n  |> filter(fn: (r) => r[\"_field\"] == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Previous: r._value * 0.001}))\n  |> yield(name: \"previous\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_device\"] == \"line\")\n  |> filter(fn: (r) => r[\"_field\"] == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Current: r._value * 0.001}))\n  |> yield(name: \"current\")\n"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"cs24\")\n  |> range(start: -60d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_device\"] == \"line\")\n  |> filter(fn: (r) => r[\"_field\"] == \"today\")\n  |> movingAverage(n: 30)\n  |> map(fn: (r) => ({ _time: r._time, MovingAverage: r._value * 0.001}))\n  |> yield(name: \"moving-average\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kitchen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"kitchen\" and r._field != \"outlets_1\" and r._field != \"outlets_2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"the_rest\")"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"kitchen\" and r._field == \"outlets_1\" or r._field == \"outlets_2\")\n  |> truncateTimeColumn(unit: 10s)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.outlets_1 + r.outlets_2 }))\n  |> drop(columns: [\"outlets_1\", \"outlets_2\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"outlets\")\n"
    }
   ]
  },
  {
   "title": "Current Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"line\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Net Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "production = from(bucket: \"multisma2\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"power\" and r._inverter == \"site\")\n  |> drop(columns: [\"_inverter\", \"_measurement\", \"_start\", \"_stop\"])\n  |> last()\n  |> yield(name: \"production\")\n  \nconsumption = from(bucket: \"cs24\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"line\")\n  |> map(fn: (r) => ({ r with _time: r._time, _value: r._value * -1.0 }))\n  |> drop(columns: [\"_measurement\", \"_start\", \"_stop\"])\n  |> last()\n  |> yield(name: \"consumption\")\n\nunion(tables: [production, consumption])\n  |> truncateTimeColumn(unit: 10m)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with Delta: float(v: r.power) + r.line }))\n  |> yield(name: \"union\")\n"
    }
   ]
  },
  {
   "title": "Living Room",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -1mo, f: \"month\"}, Year: {p: -1y, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"_main_floor\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n  |> yield(name: \"_main_floor\")\n"
    }
   ]
  },
  {
   "title": "Laundry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"laundry\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"laundry\")"
    }
   ]
  },
  {
   "title": "EV Charging",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_location\"] == \"vehicles\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"vehicles\")"
    }
   ]
  }
 ]
}