{
 "title": "CS/ESPHome Sample Panels",
 "description": "Sample dashboard for the CS/ESPHome repo",
 "tags": [
  "ESPHome",
  "multisma2"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   { "name": "period", "label": "Display Period", "query": "Today, Month, Year" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Net Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "production = from(bucket: \"multisma2\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"power\" and r._inverter == \"site\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ _time: r._time, _value: float(v: r._value), _device: r._inverter }))\n  |> yield(name: \"production\")\n  \nconsumption = from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._device == \"line\" and r._field == \"sample\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _device: r._device}))\n  |> yield(name: \"consumption\")\n\nunion(tables: [production, consumption])\n  |> truncateTimeColumn(unit: 1m)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> fill(column: \"site\", value: 0.0)\n  |> sort(columns: [\"_time\"], desc: false)\n  |> map(fn: (r) => ({ _time: r._time, \"Net Power\": r.site - r.line }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, column: \"Net Power\")\n  |> drop(columns: [\"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "title": "Current Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._device == \"line\" and r._field == \"sample\")\n  |> map(fn: (r) => ({ _time: r._time, Line: r._value }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, column: \"Line\", createEmpty: false)\n  |> drop(columns: [\"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "title": "Net Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "production = from(bucket: \"multisma2\")\n  |> range(start: -30m)\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"power\" and r._inverter == \"site\")\n  |> map(fn: (r) => ({ _value: float(v: r._value) }))\n  |> yield(name: \"production\")\n\nconsumption = from(bucket: \"cs24\")\n  |> range(start: -10m)\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"power\" and r._device == \"line\" and r._field == \"sample\")\n  |> map(fn: (r) => ({ _value: r._value * -1.0 }))\n  |> yield(name: \"consumption\")\n  \nunion(tables: [production, consumption])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ Delta: r._value }))\n"
    }
   ]
  },
  {
   "title": "Current Production",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"multisma2\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"power\" and r._inverter == \"site\")\n  |> map(fn: (r) => ({ _time: r._time, \"Production\": r._value }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, column: \"Production\", createEmpty: false)\n  |> drop(columns: [\"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"multisma2\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"production\" and r._inverter == \"site\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _kwh: (float(v: r._value) * 1.0) }))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Kitchen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._location == \"kitchen\" and r._field == lookup.${period}.f and not (exists r._device))\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Heat pump",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"heatpump\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Hot water",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"hot_water\" and r._field == lookup.${period}.f)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "EVs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._location == \"vehicles\" and r._field == lookup.${period}.f and not (exists r._device))\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Basement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._location == \"basement\" and r._field == lookup.${period}.f and not (exists r._device))\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Laundry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._location == \"laundry\" and r._field == lookup.${period}.f and not (exists r._device))\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Main Floor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._location == \"main_floor\" and r._field == lookup.${period}.f and not (exists r._device))\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Garage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._location == \"garage\" and r._field == lookup.${period}.f and not (exists r._device))\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Bedrooms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._location == \"bedroom\" and r._field == lookup.${period}.f and not (exists r._device))\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value * 0.001}))\n"
    }
   ]
  },
  {
   "title": "Utility Meter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utility Meter Reading",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"today\" and exists r._meter)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_meter\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.delta_wh + r.reading) * 0.001 }))\n  |> map(fn: (r) => ({ Meter: if r._value > 100000.0 then r._value - 100000.0 else r._value }))\n"
      }
     ]
    },
    {
     "title": "Utility Meter Daily Change",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._meter == \"delta_wh\" and r._field == \"today\")\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001 }))\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "30 Day Trend",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "kWh" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"multisma2\")\n  |> range(start: -31d)\n  |> filter(fn: (r) => r._measurement == \"production\" and r._inverter == \"site\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Production: r._value }))\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "query": "from(bucket: \"cs24\")\n  |> range(start: -31d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Consumption: r._value * -0.001}))\n"
      },
      {
       "query": "c1 = from(bucket: \"cs24\")\n  |> range(start: -60d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"today\")\n  |> movingAverage(n: 30)\n  |> map(fn: (r) => ({ _time: r._time, _movavg: r._value * -0.001}))\n  |> yield(name: \"c1\")\n\nm1 = from(bucket: \"multisma2\")\n  |> range(start: -60d)\n  |> filter(fn: (r) => r._measurement == \"production\" and r._inverter == \"site\" and r._field == \"today\")\n  |> movingAverage(n: 30)\n  |> map(fn: (r) => ({ _time: r._time, _movavg: r._value }))\n  |> yield(name: \"m1\")\n\njoin(tables: {d1: c1, d2: m1}, on: [\"_time\"])\n  |> drop(columns: [\"_movavg\"])\n  |> map(fn: (r) => ({ _time: r._time, \"30 day average\": r._movavg_d1 + r._movavg_d2}))\n"
      }
     ]
    },
    {
     "title": "12 Month Consumption",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "kWh" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"cs24\")\n  |> range(start: -13mo, stop: -1mo)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"month\")\n  |> map(fn: (r) => ({ _time: r._time, Previous: r._value * 0.001}))\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "query": "from(bucket: \"cs24\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"month\")\n  |> map(fn: (r) => ({ _time: r._time, \"Current\": r._value * 0.001}))\n"
      }
     ]
    },
    {
     "title": "30 Day Consumption",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "kWh" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"cs24\")\n  |> range(start: -31d, stop: -1d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Previous: r._value * 0.001}))\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, Current: r._value * 0.001}))\n"
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"cs24\")\n  |> range(start: -60d)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._device == \"line\" and r._field == \"today\")\n  |> movingAverage(n: 30)\n  |> map(fn: (r) => ({ _time: r._time, MovingAverage: r._value * 0.001}))\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Current Power Consumption (W)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"kitchen\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, \"Kitchen\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"vehicles\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, \"EVs\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._device == \"heatpump\" and r._field == \"sample\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, \"Heat Pump\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._device == \"hot_water\" and r._field == \"sample\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, \"Hot Water\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"basement\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, \"Basement\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"garage\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, \"Garage\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"laundry\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, \"Laundry\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"bedroom\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, \"Bedrooms\": r._value }))\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"main_floor\" and r._field == \"today\")\n  |> map(fn: (r) => ({ _time: r._time, \"Main Floor\": r._value }))\n"
    }
   ]
  },
  {
   "title": "Line Characteristics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"sample\")\n  |> filter(fn: (r) => r._device == \"line\" or r._device == \"l1\" or r._device == \"l2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Heat Pump & Hot Water",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._device == \"hot_water\" and r._field == \"sample\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._device == \"heatpump\" and r._field == \"sample\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Kitchen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"kitchen\" and r._field == \"sample\")\n  |> filter(fn: (r) => r._device != \"outlets_1\" and r._device != \"outlets_2\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"kitchen\")\n  |> filter(fn: (r) => r._device == \"outlets_1\" or r._device == \"outlets_2\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_device\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.outlets_1 + r.outlets_2 }))\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\", \"outlets_1\", \"outlets_2\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Laundry",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"laundry\" and r._field == \"sample\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "EV Charging",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"vehicles\" and r._field == \"sample\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Bedrooms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"bedroom\" and r._field == \"sample\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Main Floor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"main_floor\" and r._field == \"sample\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Garage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"cs24\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" and r._location == \"garage\" and r._field == \"sample\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_location\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "${period}",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "repeat": "Periods",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => (r._location == \"kitchen\" and not exists r._device) or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if exists r._location then \"numerator\" else \"denominator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Kitchen\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => (r._location == \"basement\" and not exists r._device) or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if exists r._location then \"numerator\" else \"denominator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Basement\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => (r._location == \"vehicles\" and not exists r._device) or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if exists r._location then \"numerator\" else \"denominator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"EV Charging\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => (r._location == \"basement\" and not exists r._device) or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if exists r._location then \"numerator\" else \"denominator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Bedrooms\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => (r._location == \"laundry\" and not exists r._device) or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if exists r._location then \"numerator\" else \"denominator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Laundry\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => (r._location == \"main_floor\" and not exists r._device) or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if exists r._location then \"numerator\" else \"denominator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Main Floor\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => (r._location == \"garage\" and not exists r._device) or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if exists r._location then \"numerator\" else \"denominator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Garage\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => r._device == \"hot_water\" or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if r._device == \"line\" then \"denominator\" else \"numerator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Hot Water\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => r._device == \"heatpump\" or r._device == \"line\")\n  |> last()\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _ratio: if r._device == \"line\" then \"denominator\" else \"numerator\" }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_ratio\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Heat Pump\":\n      if not exists r.denominator or r.denominator == 0.0 then 0.0\n      else r.numerator / r.denominator * 100.0 } ))\n"
      }
     ]
    },
    {
     "title": "${period} Use (kWh) ",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 14, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"kitchen\" and not exists r._device)\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, Kitchen: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"basement\" and not exists r._device)\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, Basement: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"vehicles\" and not exists r._device)\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, EVCharging: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"bedroom\" and not exists r._device)\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, Bedrooms: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"main_floor\" and not exists r._device)\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, MainFloor: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"laundry\" and not exists r._device)\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, Laundry: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"garage\" and not exists r._device)\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, Garage: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"hot_water\")\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, HotWater: r._value * 0.001 } ))\n  |> toString()\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._device == \"heatpump\")\n  |> last()\n  |> map(fn: (r) => ({ _value: r._device, Heatpump: r._value * 0.001 } ))\n  |> toString()\n"
      }
     ]
    },
    {
     "title": "${period} Use (kWh) ",
     "type": "bargauge",
     "gridPos": { "h": 1, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"vehicles\" and r._device == \"tesla\")\n  |> last()\n  |> map(fn: (r) => ({ \"Tesla\": r._value * 0.001, _value: r._device }))\n  |> toString()\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_field\"])\n"
      },
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f and r._location == \"vehicles\" and r._device == \"juicebox\")\n  |> last()\n  |> map(fn: (r) => ({ \"Nissan Leaf\": r._value * 0.001, _value: r._device }))\n  |> toString()\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_field\"])\n"
      }
     ]
    },
    {
     "title": "${period} Use (kWh)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 14, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "lookup = {Today: {p: -1d, f: \"today\"}, Month: {p: -32d, f: \"month\"}, Year: {p: -13mo, f: \"year\"}}\nfrom(bucket: \"cs24\")\n  |> range(start: lookup.${period}.p)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == lookup.${period}.f)\n  |> filter(fn: (r) => r._device == \"heatpump\" or\n                       r._device == \"hot_water\" or\n                       (r._location == \"kitchen\" and not exists r._device) or\n                       (r._location == \"laundry\" and not exists r._device) or\n                       (r._location == \"bedroom\" and not exists r._device) or\n                       (r._location == \"basement\" and not exists r._device) or\n                       (r._location == \"main_floor\" and not exists r._device) or\n                       (r._location == \"garage\" and not exists r._device) or\n                       (r._location == \"vehicles\" and not exists r._device)\n                    )\n  |> last()\n  |> map(fn: (r) => ({ kWh: r._value * 0.001, _value: if exists r._device then r._device else r._location }))\n  |> toString()\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"_field\"])\n"
      }
     ]
    }
   ]
  }
 ]
}