# YAML configuration file for configuring the application to connect to the
# ESPHome API and subscribe to energy sensor updates from the CircuitSetup hardware.
cs_esphome:
  # debug fields (requires CS_ESPHOME_DEBUG to be set to True or 1 to be in effect)
  #  debug.create_bucket    creates the InfluxDB2 bucket if it does not exist (bool)
  #  debug.delete_bucket    deletes the bucket if it exists (bool)
  #  debug.recreate_tasks   remove all InfluxDB tasks and create new ones (bool)
  #  debug.fill_data        fills in today/month/year energy fields to 0 (bool)
  #
  #  This last option can fill in the today/month/year energy records to make your long-term
  #  Grafana graphs filled.  Use a smart fill in queries the database for the first entry
  #  so not to overwrite any existing entries.  Will fill in a 13 months worth of data.
  debug:
    create_bucket:  False
    delete_bucket:  False
    recreate_tasks: False
    fill_data:      False

  # This option is used the current meter reading
  meter:
    enable_setting: False
    value:          95443

  # ESPHome API fields
  # These options are used to login into the ESPHome API to collect the sensor data.
  #   circuitsetup.url        set to the ESPHome API url ('str')
  #   circuitsetup.port       optional ESPHome API port, defaults to 6053 ('int')
  #   circuitsetup.password   optional ESPHome API password, defaults to '' ('str')
  circuitsetup:
    url:          !secret circuitsetup_url
    port:         !secret circuitsetup_port
    password:     !secret circuitsetup_password

  # InfluxDB setup
  # The InfluxDB interface requires the following options.
  #   influxdb2.enable        set to True to enable InfluxDB output ('bool')
  #   influxdb2.bucket        set to the InfluxDB bucket ('str')
  #   influxdb2.url           set to the InfluxDB server URL and port ('str')
  #   influxdb2.org           set to the v2 organization ('str')
  #   influxdb2.token         set to a valid v2 token ('str')
  influxdb2:
    org:    !secret influxdb2_org
    url:    !secret influxdb2_url
    bucket: !secret influxdb2_bucket
    token:  !secret influxdb2_token

  # CS/ESPHome settings
  # Allows some settings to be modified without editing the code
  # settings.sampling defines how often the various processing loops run
  #   settings.sampling.integrations    period (seconds) for updating integrations (int)
  #   settings.watchdog                 override the default watchdog timer timeout (int)
  settings:
    sampling:
      integrations: 30
    watchdog:   30

  # Sensor setup
  # Sensors are a list of one or more sensors in the ESPHome subscription.
  #   sensor.enable         optional, defaults to True if not present
  #   sensor.sensor_name    set to the CS sensor name ('str')
  #   sensor.display_name   set to the desired display name ('str')
  #   sensor.measurement    set to the InfluxDB _measurement ('str')
  #   sensor.tag            set to an optional InfluxDB tag ('str')
  #   sensor.field          set to the InfluxDB field ('str')
  sensors:
    - sensor:
        enable:         True
        sensor_name:    'cs24_volts'
        display_name:   'Line Voltage'
        measurement:    'voltage'
        device:         'line'
        location:       ''
    - sensor:
        enable:         True
        sensor_name:    'cs24_volts_ph1'
        display_name:   'Phase 1 Voltage'
        measurement:    'voltage'
        device:         'l1'
        location:       ''
    - sensor:
        enable:         True
        sensor_name:    'cs24_volts_ph2'
        display_name:   'Phase 2 Voltage'
        measurement:    'voltage'
        device:         'l2'
        location:       ''
    - sensor:
        enable:         False
        sensor_name:    'cs24_frequency'
        display_name:   'Line Frequency'
        measurement:    'frequency'
        device:         'frequency'
        location:       ''
    - sensor:
        sensor_name:    'cs24_pf1'
        display_name:   'Power Factor'
        measurement:    'power_factor'
        device:         'pf'
        location:       ''
    - sensor:
        sensor_name:    'cs24_w'
        display_name:   'Total load'
        measurement:    'power'
        device:         'line'
        location:       ''
        integrate:      True
    - sensor:
        sensor_name:    'cs24_metered_w'
        display_name:   'Metered circuits'
        measurement:    'power'
        device:         'metered'
        location:       ''
        integrate:      True

    # Individual CTs
    - sensor:
        sensor_name:    'cs24_ct11_w'
        display_name:   'L1 Power'
        measurement:    'power'
        device:         'l1'
        location:       ''
    - sensor:
        sensor_name:    'cs24_ct12_w'
        display_name:   'L2 Power'
        measurement:    'power'
        device:         'l2'
        location:       ''
    - sensor:
        sensor_name:    'cs24_ct13_w'
        display_name:   'Tesla HPWC'
        measurement:    'power'
        device:         'tesla'
        location:       'vehicles'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct14_w'
        display_name:   'Datacenter'
        measurement:    'power'
        device:         'datacenter'
        location:       'basement'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct15_w'
        display_name:   'Basement East'
        measurement:    'power'
        device:         'east_basement'
        location:       'basement'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct16_w'
        display_name:   'Dryer'
        measurement:    'power'
        device:         'dryer'
        location:       'laundry'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct21_w'
        display_name:   'Heat pump'
        measurement:    'power'
        device:         'heatpump'
        location:       ''
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct22_w'
        display_name:   'Washer'
        measurement:    'power'
        device:         'washer'
        location:       'laundry'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct23_w'
        display_name:   'Hot water'
        measurement:    'power'
        device:         'hot_water'
        location:       ''
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct24_w'
        display_name:   'JuiceBox'
        measurement:    'power'
        device:         'juicebox'
        location:       'vehicles'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct25_w'
        display_name:   'Range'
        measurement:    'power'
        device:         'range'
        location:       'kitchen'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct26_w'
        display_name:   'Microwave'
        measurement:    'power'
        device:         'microwave'
        location:       'kitchen'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct31_w'
        display_name:   'Sump pump'
        measurement:    'power'
        device:         'sump'
        location:       'basement'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct32_w'
        display_name:   'Main Bedroom'
        measurement:    'power'
        device:         'main'
        location:       'bedroom'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct33_w'
        display_name:   'Refrigerator'
        measurement:    'power'
        device:         'refrigerator'
        location:       'kitchen'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct34_w'
        display_name:   'GFI Outlets'
        measurement:    'power'
        device:         'outlets_1'
        location:       'kitchen'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct35_w'
        display_name:   'GFI Outlets'
        measurement:    'power'
        device:         'outlets_2'
        location:       'kitchen'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct36_w'
        display_name:   'Dishwasher'
        measurement:    'power'
        device:         'dishwasher'
        location:       'kitchen'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct41_w'
        display_name:   'Guest bedrooms'
        measurement:    'power'
        device:         'guest'
        location:       'bedroom'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct42_w'
        display_name:   'Living room'
        measurement:    'power'
        device:         'living_room'
        location:       'main_floor'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct43_w'
        display_name:   'Foyer/bath'
        measurement:    'power'
        device:         'foyer'
        location:       'main_floor'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct44_w'
        display_name:   'Refrigerator'
        measurement:    'power'
        device:         'refrigerator'
        location:       'basement'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct45_w'
        display_name:   'Garage/Freezer'
        measurement:    'power'
        device:         'garage'
        location:       'garage'
        integrate:      True
    - sensor:
        sensor_name:    'cs24_ct46_w'
        display_name:   'Basement'
        measurement:    'power'
        device:         'west_basement'
        location:       'basement'
        integrate:      True
